name: sysinfo actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.17.1

    - name: Install dependencies
      run: npm ci

    - name: Lint and format
      run: npm run fix

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
